cowin:
  baseUrl : https://cdn-api.co-vin.in/api/v2/
  districtURI: appointment/sessions/calendarByDistrict?
  districtParam: district_id
  date: date
  selectedDistrict: pune

telegram:
    tBaseUrl: https://api.telegram.org
    tApiKey: <TODO - API KEY HERE>
    tChannelName : <TODO channel name here>

districts:
  all:
    pune: 363
    ahmednagar: 391
    akola: 364
    amravati: 366
    aurangabad: 397
    beed: 384
    bhandara: 370
    buldhana: 367
    chandrapur: 380
    dhule: 388
    gadchiroli: 379
    gondia: 378
    hingoli: 386
    jalgaon: 390
    jalna: 396
    kolhapur: 371
    latur: 383
    mumbai: 395
    nagpur: 365
    nanded: 382
    nandurbar: 387
    nashik: 389
    osmanabad: 381
    palghar: 394
    parbhani: 385
    raigad: 393
    ratnagiri: 372
    sangli: 373
    satara: 376
    sindhudurg: 374
    solapur: 375
    thane: 392
    wardha: 377
    washim: 369
    yavatmal: 368
